// Assignment Code
var generateBtn = document.querySelector("#generate");

function generatePassword() {
  var possiblespecial = "!#$%&()*+,-./:;<=>?@[]^_`{|}~"
  var letters = "abcdefghijklmnopqrstuvwxyz";
  var numbers = "0293428294308723";
  var upLetters = letters.toUpperCase();
  var chooseFrom = "";
  // YOUR CODE GOES HERE
  var passwordLength = prompt("How long do you want your password to be? Between 8 and 128 characters.") 
  if (passwordLength <8 || passwordLength >128) {
alert ("Password length invalid.")
generatePassword() 
  }
  console.log(passwordLength)
  var isUppercase = confirm("Would you like to use uppercase?");
  var isLowercase = false;  
  var isSpecial = false;
  var isNumber = false;

  if (isUppercase) {
    // use uppercase letters 
    console.log("uppercase");
    chooseFrom += upLetters;
  }
  if (isLowercase) {
    // use lowercase letters 
    console.log("lowercase");
  }

  if (isSpecial) {
    // use special characters
    console.log("speical"); 
  }
  if (isNumber) {
    // use numbers
    console.log("numbers");
  }

// grab random letters 
console.log(chooseFrom.length);
if (chooseFrom.length === 0) {
  alert ("You must choose at least one character type.")
  generatePassword()
}

  return "A password to be generated by this function";
}

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
