// Assignment Code
var generateBtn = document.querySelector("#generate");

function generatePassword() {
  var possiblespecial = "!#$%&()*+,-./:;<=>?@[]^_`{|}~"
  var letters = "abcdefghijklmnopqrstuvwxyz";
  var numbers = "0293428294308723";
  var upLetters = letters.toUpperCase();
  var chooseFrom = "";
  var newPass = "";
  // YOUR CODE GOES HERE
  var passwordLength = prompt("How long do you want your password to be? Between 8 and 128 characters.") 
  if (passwordLength <8 || passwordLength >128) {
alert ("Password length invalid.")
generatePassword() 
  }
  console.log(passwordLength)
  var isUppercase = confirm("Would you like to use uppercase?");
  var isLowercase = confirm("Would you like to use lowercase?");  
  var isSpecial = confirm("Would you like to use special characters?");
  var isNumber = confirm("Would you like to use numbers?");

  if (isUppercase) {
    // use uppercase letters 
    chooseFrom += upLetters;
  }
  if (isLowercase) {
    // use lowercase letters 
    chooseFrom += letters;
  }

  if (isSpecial) {
    // use special characters
    chooseFrom += possiblespecial;
  }
  if (isNumber) {
    // use numbers
    chooseFrom += numbers;
  }

// grab random letters 

// wrap in a for loop

// for (var i = 0; i > 8 && i < 128; i++) {
// console.log(chooseFrom.length);
// var random = Math.floor(Math.random() * chooseFrom.length);
// console.log(chooseFrom[random])

for (i = 0; i < isPassLength; i++) {
  var randomGeneration = Math.floor(Math.random() * chooseFrom.length);
  var passChar = chooseFrom.charAt(randomGeneration);
  newPass = newPass.concat(passChar);
  }
  return newPass;

generatePassword()

// if (chooseFrom.length === 0) {
  // alert ("You must choose at least one character type.")
  // generatePassword()
}
  return chooseFrom;
  // return "A password to be generated by this function";
  
  
  //return the variable with the password you created using a for loop

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
